apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceconfig
data:
  MONGO_USERNAME: admin
  MONGO_PASSWORD: Pa55w0rd
  NODE_ENV: PRODUCTION
  MONGO_HOST: mongo
  MONGO_DATABASE: berkadia
  NODE_ENV: PRODUCTION

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: berkadia-api
  labels:
    app: berkadia-api
spec:
  selector:
    matchLabels:
      app: berkadia-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: berkadia-api
    spec:
      containers:
      - name: berkadia-api
        image: node_berkadia
        imagePullPolicy: Never
        envFrom:
         - configMapRef:
             name: serviceconfig
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: berkadia-api
  name: berkadia-api
spec:
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
    nodePort: 31509
  selector:
    app: berkadia-api
  type: NodePort
