---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/my-database"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongoconfig
data:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: Pa55w0rd  
---
apiVersion: v1
kind: Service
metadata:
   name: mongo
   labels:
     run: mongo
spec:
  ports:
  - name: "http"
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    run: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongo
spec:
   selector:
    matchLabels:
      run: mongo
   template:
     metadata:
       labels:
         run: mongo
     spec:
      containers:
       - name: mongo
         image: mongo
         ports:
         - containerPort: 27017 
         envFrom:
         - configMapRef:
             name: mongoconfig
         volumeMounts:
         - name: persistent-db-storage
           mountPath: /data/db
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: mongo-pvc  
